import time
import random


#LEVEL FOUR: PYTHON JUNGLE

def scenario_two():
    print("")
    print("...")
    print("")
    time.sleep(1)
    print("")
    print("...")
    print("")
    time.sleep(1)
    print("")
    print("...")
    print("")
    time.sleep(1)
    print("***The python attacks!***")
    print("")
    time.sleep(1)
    print("                  ____        ")
    print("                 / . .\      ")
    print("                 \  ---<       ")
    print("                  \  /")
    print("        __________/ /")
    print("     <//___________/")
    print("")
    print("")
    response = input("What are you going to do? [Attack/Dodge/Jump attack]")
    if response == "Dodge" or response == "DODGE" or response == "dodge":
                    print("")
                    
                    num = random.randint(1, 10)
                    if num <5:
                        
                        print("***You try to dodge the python but it thrashes toward you at the speed of light and you are too slow...***")
                        print("")
                        print("***The python wraps itself around you and swallows you whole***")
                        print("")
                        print("*** GAME OVER ***")
                        print("")
                        response = input("Play again? [Yes/No]")
                        if response == "yes" or response == "YES" or response == "Yes":
                          level_four_opening() 
                        else:
                            print("***Thank you for playing PYTHON JUNGLE " + name.upper() + "!***")
                            print(" ")
                            time.sleep(2)
                            print("Try not to wake up here again...")   
                    else:    
                        print("***You manage to dodge the python’s attack by a very lucky millimetre!!***") 
                        scenario_two()
    elif response == "attack":
        print("***Trembling, you grip your sword with white knuckles...***")
        time.sleep(1)
        print(" ")
        print("***You swipe at the python with your sword!***")
        print("") 
        time.sleep(1)
        print("")
        print("***It's not very effective... And now the python is even more angry!***")
        print("")
        scenario_two()
    elif response == "jump attack" or response == "Jump attack" or response == "jumpattack" or response == "JUMP ATTACK":
        print("")
        print("***You jump on top of the pythons head, feeling like you are surfing the most vicious of oceans...***")
        print("")
        time.sleep(2)
        print("***You drive your sword downwards into the python's concrete skull...***")
        print("")
        time.sleep(2)
        print("***Your sword bends as if about to snap...***")
        print("")
        time.sleep(2)
        print("***You close your eyes and keep pushing the sword, scared to ever open them again...***")
        print("")
        time.sleep(2)
        print("***Then you realise...***") 
        print("")
        print("")
        time.sleep(1)
        print("...")
        print("")   
        time.sleep(1)
        print("...")
        print("")   
        time.sleep(1)
        print("...")
        print("")   
        print("***You have defeated the python!***")
        print("")
        print("                  ____        ")
        print("                 / X X\      ")
        print("                 \  ---<       ")
        print("                  \  /")
        print("        __________/ /")
        print("     <//___________/")
        print("")
        print("")
        time.sleep(1)
        print("*******************************************************************************************************")
        print("You stumble out of the temple, and begin to make your way out of the jungle...")
        print("")
        time.sleep(2)
        print("Every muscle and bone aches. You can hardly believe that the python is defeated, that this is over...") 
        print("")
        time.sleep(2)
        print("In some twisted way, you will miss this place. But not enough to stay for another second.") 
        print("")
        time.sleep(2)
        print("You are victorious!")
        print("")
        time.sleep(2)
        print("*******************************************************************************************************")
        print("Congratulations! You have won PYTHON JUNGLE!!")
        print("")
        print("")
        print("")
        response = input("Play again? [Yes/No] ")
        if response == "yes" or response == "YES" or response == "Yes":
                        game_start()
        else:
            print("~~~ Thank you for playing Python Jungle! ~~~")
            quit()





def scenario_one():
    
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("A giant python appears!")
    print("")
    time.sleep(2)
    print("Its thrashing body outsizing a train carriage, its intricate scales almost camouflaging against the mosaic of the temple surrounding you...")

    time.sleep(1)
    print("                  ____        ")
    print("                 / . .\      ")
    print("                 \  ---<       ")
    print("                  \  /")
    print("        __________/ /")
    print("     <//___________/")
    print("")
    time.sleep(1)
    print("")
    print("The python rises in fury with a hiss like the blackest thunderstorm...")
    print("")
    time.sleep(2)
    print("THE PYTHON ATTACKS!")
    print("")
    time.sleep(2)
    response = input("What are you going to do?!! [Attack/Dodge]")
    if response == "Dodge" or response == "DODGE" or response == "dodge":
                    print("")
                    
                    num = random.randint(1, 2)
                    if num == 1:
                        
                        print("***You scramble away from the python, trying to dodge its wrath...***")
                        print("")
                        time.sleep(1)
                        print("***But bad luck...***")
                        print("")
                        time.sleep(1)
                        print("***You are killed by the python***")
                        print("")
                        print("*** GAME OVER ***")
                        print("")
                        response = input("Play again? [Yes/No]")
                        if response == "yes" or response == "YES" or response == "Yes":
                          level_four_opening() 
                        else:
                            print("***Thank you for playing PYTHON JUNGLE!***")
                            quit()
                               
                    else:    
                        print("***You manage to dodge the python's attack by a very lucky millimetre!!!***") 
                        scenario_one()
    else:
                print("***You attack the python!***")
                print("")
                time.sleep(1)
                print("...")
                time.sleep(1)
                print("")
                print("******************************************************************")
                print("Your attack bounces off the hard scales on the pythons stomach...")
                print("")
                time.sleep(1)
                print("Your sword may as well be a feather when contending with the solid mosaic skin of the python...")
                print("")
                time.sleep(1)
                print("The python circles you, still very much alive, its hissing tongue whipping up a tornado...")
                time.sleep(1)
                print("")
                print("*****************************************************************")
                time.sleep(1)
                print("***You realise the temple altar is behind you...***")
                print("")
                print("***It seems like you may be able to climb it and gain some advantage over this ravenous, cunning beast...***")
                print("")
                print("Will you attack the python again or attempt to climb the altar?")
                print("")
                print("*****************************************************************")
                response = input("What are you going to do? [Attack/Climb]")
                if response == "Attack" or response == "ATTACK" or response == "attack":
                    print("")
                    time.sleep(1)
                    print("***The python hurtles toward you, with a jaw that could crush the temple itself...***")
                    print("")
                    time.sleep(2)
                    print("***You try desperately to defend yourself, engaging every neurone of your brain...***")
                    print("")
                    time.sleep(2)
                    print("***You try to defend yourself but are thrown to the floor by pure fright...***")
                    print("")
                    time.sleep(1)
                    print("...")
                    ("")
                    time.sleep(1)
                    print("...")
                    ("")
                    time.sleep(1)
                    print("...")
                    print("")
                    time.sleep(1)
                    print("***You are killed by the effortless power of the python!***")
                    print("")
                    print("*** GAME OVER ***")
                    print("")
                    response = input("Play again? [Yes/No]")
                    if response == "yes" or response == "YES" or response == "Yes":
                        level_four_opening()
                    else:
                        print("***Thank you for playing PYTHON JUNGLE!***")
                        quit()

                elif response == "Climb" or response == "climb" or response == "CLIMB":
                    print("")
                    print("***You run to the centre of the room and scramble up the altar***")
                    print("")
                    scenario_two()
                   



def door_sequence():
    print("**************************************************************************")
    print("")
    print("***You dodge past the chest without taking anything from it and head towards the mosaic door...***")
    print("")
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("...")
    print("")
    time.sleep(1)
    print("Just as you begin wedging open the door, a giant python appears with earthquakes in its furious eyes! ")

    time.sleep(1)
    print("                  ____        ")
    print("                 / . .\      ")
    print("                 \  ---<       ")
    print("                  \  /")
    print("        __________/ /")
    print("     <//___________/")
    print("")
    time.sleep(1)
    print("")
    print("")
    print("You are weaponless and terrified, and try to fight the python with your hands...")
    print("")
    time.sleep(1)
    print("...")
    print("")
    print("***You are killed by the python***")
    print("")
    print("*** GAME OVER ***")
    print("")
    response = input("Play again? [Yes/No]")
    if response == "yes" or response == "YES" or response == "Yes":
        level_four_opening()
    else:
        print("***Thanks for playing PYTHON JUNGLE!***")
        quit()


def chest_sequence():
            print("You approach the chest as the inch-thick layer of dust from its surface swirls in the air... Looks like something interesting could be inside!")
            response = input("Open the chest? [Yes/No]")
            if response == "Yes" or response == "yes":
                    print("*You force open the rusty bolt of the chest and find the following items...*")
                    print("")   
            elif response == "No" or response == "no" or response == "NO": 
                door_sequence()     

            def treasure_chest1():
                print("sword")

            def treasure_chest2():
                print ("diamonds")


            treasure_chest = ["diamonds", "sword"]
            for treasure in treasure_chest:
                    print(treasure)
 

            print("")
            print("Take all {} treasures, press '1 or type item name'".format(len(treasure_chest)))

            response = input("")
            if response == "1":
                    print("You have removed {} items from the chest".format(len(treasure_chest)))
                    print("")
                    time.sleep(1)
                    print("**You close the chest**")
                    time.sleep(1)
                    print("**sword* and *diamonds* have been added to your backpack**")
                    print("")
                    scenario_one()
                    

            elif response == "diamonds" or response == "Diamonds" or response == "diamond":
                print("You have removed {} item from the chest".format(len(treasure_chest)-1)) 
                response = input("Take another item from the chest? [Yes/No]")
                if response == "Yes" or response == "yes":
                    print("*You force open the rusty bolt of the chest and find the following items...*")
                    treasure_chest1()
                    time.sleep(1)
                    print("**sword* has been added to your backpack**")
                    print("")
                    print("**You close the chest**")
                    scenario_one()
                elif response == "no" or response == "No":
                    time.sleep(1)
                    print("**You close the chest**")
                    scenario_one()

            elif response == "sword" or response == "swords":
                print("You have removed {} item from the chest".format(len(treasure_chest)-1)) 
                response = input("Take another item from the chest? [Yes/No]")
                if response == "Yes" or response == "yes":
                    print("*You force open the rusty bolt of the chest and find the following items...*")
                    treasure_chest2()
                    time.sleep(1)
                    print("**diamonds* has been added to your backpack*")
                    time.sleep(1)
                    print("")
                    print("**You close the chest**")
                    scenario_one()
                elif response == "no" or response == "No":
                    door_sequence()    

def level_four_start():
    print("")
    print("")
    print("***************************************************************************")
    print(" Entering the temple, you find yourself in a large room covered floor to ceiling in the most intricate mosaic, with every shade of green ever known to man or python...")
    print("")
    time.sleep(2)
    print("It almost feels as though you could be in the belly of the python itself...")
    print("")
    time.sleep(2)
    print("In the centre of the room stands an almighty altar, both heavenly and demonic all at the same time...")
    print("")
    time.sleep(2)
    print("There is a large chest in front of you. It looks as though it has survived 1,000 world wars and is covered in a thick layer of jungle dust...")
    print("")
    time.sleep(2)
    print("It seems like something interesting could be inside...")
    print("")
    time.sleep(1)
    print("Behind the chest is a green mosaic door. Maybe it leads out of the jungle...?")
    print("")
    print("***************************************************************************")
    print("")
    print("Do you open the chest or head straight to the door?")

    response = input("[Chest/Door]")
    if response == "Chest" or response == "chest" or response == "CHEST":
        chest_sequence()

    elif response == "Door" or response == "door" or response == "DOOR": 
        door_sequence()
    else:
        print("Please enter one of the above options to proceed")
    #level_four_start()     


def level_four_opening():
    time.sleep(1)
    print("")
    print("You awaken once more to the sounds of a strange place, surprised to find you are still alive...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    print("The sounds of the Python Jungle echo through the trees...")
    time.sleep(1)
    print("...")
    time.sleep(1)
    time.sleep(1)
    print("")
    response = input("Are you ready to catapult yourself into the final adventure and escape PYTHON JUNGLE?!?! [Yes/No] ")
    if response == "Yes" or response == "yes" or response == "ok" or response == "OK" or response == "Ok":
        print("")
        print("")
        print("3")
        print("")
        time.sleep(1)
        print("2")
        print("")
        time.sleep(1)
        print("1")
        print("")
        time.sleep(1)
        print("")
        print("")
        print("")

        print("***************************************************************************")
        print("  *********   *************        *          ********    **********          ")
        print("  *                 *             * *         *      *        *               ")
        print("  *                 *            *   *        *      *        *               ")
        print("  *********         *           *******       ********        *               ")
        print("          *         *          *       *      *   *           *               ")
        print("          *         *         *         *     *     *         *               ")
        print("  *********         *        *           *    *       *       *               ")
        print("***************************************************************************")
        time.sleep(2)
        level_four_start()
    else:
        level_four_opening()

    #level_four_opening()  

# import time

# def lion_decision():

#     print("Unfortunately for you, the lioness appears out of the trees!")
#     time.sleep(1)
#     print("Looks like you don't have a choice - You have to fight it!")
#     time.sleep(1)
#     print("You look in your pack and find a few weapons that you picked up along the way.")

#     response = input("Which weapon do you choose to use against the lion? [Axe / Rope / Sword] ")
#     if response == "axe" or response == "Axe":
#         print("You kill the lion using the axe!")
#         wake_up_in_the_jungle()
#     elif response == "rope" or response == "Rope":
#         print("You kill the lion using the rope!")
#         wake_up_in_the_jungle()
#     elif response == "Sword" or response == "sword":
#         print("You kill the lion using the sword!")
#         wake_up_in_the_jungle()
#     else:
#         print("Please try again...")
#     lion_decision()

def level_4():
    print("As you close your eyes, you see the shape of a temple in the misty distance.")
    time.sleep(1)
    print("Could this be the python temple that leads to freedom from the jungle at last?")
    time.sleep(1)
    print("You feel yourself losing consciousness.")
    print("Looks like you will find out tomorrow {}...".format(name))
    level_four_opening()


def wake_up_in_the_jungle():
    time.sleep(3)
    print("Although you managed to defeat the lioness, you find yourself badly wounded.")
    print("")
    time.sleep(2)
    print("You stagger around, holding your wounds.")
    print("")
    time.sleep(2)
    print("Scavenging and looting through every unopened cupboard and chest in pure desperation to find something...")
    time.sleep(2)
    print("")
    print("Anything!...")
    time.sleep(3)
    print("A sudden lack of energy has now began to eradicate you.")
    time.sleep(2)
    print("Your strength is truncating...")
    time.sleep(2)
    print("Your ability to stand - diminishing...")
    time.sleep(2)
    print("Your sight becomes more hazy with each blink...")
    time.sleep(2)
    print("Your mind is beginning to immobilise as you mumble to yourself with slurred speech")
    time.sleep(2)
    print("'Could this be it {}!?...'".format(name))
    time.sleep(2)
    print("You fall to your knees and notice a small, weathered box on the ground")
    time.sleep(2)
    print("You slowly reach out, your arm trembling with the other barely able to support your weight")
    print("You open the box and find 3 items. Which one do you take?")
    response = input("The first aid kit, the coconut water or the ripe mango [A, B, C]")
    time.sleep(2)
    # if response == "First aid kit" or response == "first aid kit" or response == "The first aid kit" or response == "the first aid kit" or response == "A" or response == "a":
    if any([response.lower().endswith("first aid"), response.lower() == "a"]):
        print("You open the first aid kit and use your last ounce of energy to heal your wounds.")
        time.sleep(2)
        print("Though your wounds may be healed, you soon slowly drift off into unconciousness due to your lack of energy...")
        level_4()
    #YOU CAN NOW CALL A FUNCTION TO WAKE UP IN THE NEXT CHAPTER
    # elif response == "The coconut water" or response == "the coconut water" or response == "Coconut water" or response == "coconut water" or response == "B" or response == "b":
    elif any([response.lower().endswith("coconut water"), response.lower() == "b"]):
        print("You possess a sudden burst of energy as you fall overwhelmed with the sight of water")
        time.sleep(2)
        print("You open the cap and guzzle the water in one!")
        time.sleep(2)
        print('"Ahhhh! That was refreshing!"...')
        #print('{}: "Ahhhh! That was refreshing!...'.format(name))
        time.sleep(2)
        print("Whilst enjoying your refreshing beverage that has given you a huge morale and energy boost, your body passes out due to shock from the untreated wounds...")
        level_4()
        #FUNCTION TO TAKE YOU TO NEXT CHECKPOINT
    # elif response == "Unripen mango" or response == "unriped mango" or response == "Mango" or response == "mango" or response == "C" or response == "c":
    elif any([response.lower().endswith("mango"), response.lower() == "c"]):
        print("Your face lights up with joy!")
        time.sleep(2)
        print("You immediately pick up the mango and instantly devour it!")
        time.sleep(2)
        print("The succulent ripe mango juice trickling down the corners of your mouth, meeting at your chin, dripping off onto your clothing as you continue to finish off the delicious fruit.")
        time.sleep(2)
        print('"Ahhhh! That was refreshing!"...')
        #print('{}: "Ahhhh! That was refreshing!...'.format(name))
        print("Whilst enjoying your luscious, juicy mango that has given you a huge morale and energy boost, your body passes out due to shock from the untreated wounds...")
        level_4()
    #FUNCTION TO TAKE YOU TO NEXT CHECKPOINT
    else:
        print("Please select from the following options")
    wake_up_in_the_jungle()

# def level_4():
#     print("As you close your eyes, you see the shape of a temple in the distance.")
#     time.sleep(1)
#     print("Could this be the python temple that leads to freedom from the jungle at last?")
#     time.sleep(1)
#     print("You feel yourself loosing consciousness.")
#     print("Looks like you will find out tomorrow {}...".format(name))
    
    #level_four_opening()


def lion_decision():

    print("The next morning... You awake at sun rise to the sound of a million jungle birds singing...")
    print("")
    time.sleep(2)
    print("Or wait... Maybe they are warning calls?!... Because...")
    print("")
    time.sleep(2)
    print("...Unfortunately for you, the lioness from yesterday appears out of the trees!")
    time.sleep(1)
    print("")
    print("Looks like you don't have a choice - you have to fight it!")
    time.sleep(1)
    print("")
    print("You look in your pack and find a few weapons that you picked up along the way.")

    response = input("Which weapon do you choose to use against the lion? [Axe / Rope / Sword] ")
    if response == "axe" or response == "Axe":
        time.sleep(2)
        print("You raise the axe into the sky and bring it down with all of your force, managing to kill the lion!")
        wake_up_in_the_jungle()
    elif response == "rope" or response == "Rope":
        time.sleep(2)
        print("With a huge stroke of luck from the Python Jungle Gods, you manage to kill the lion using the rope!")
        wake_up_in_the_jungle()
    elif response == "Sword" or response == "sword":
        time.sleep(2)
        print("You unleash the mighty sword and slash it at the lion, killing it!")
        wake_up_in_the_jungle()
    else:
        print("Please try again...")
    lion_decision()


# import time

def lake_decision():
    lake_answer = input("Do you decide to get into the lake with piranhas, or stay on shore with the lioness? [Piranha / Lioness] ---  ")
    if lake_answer == "Piranha" or lake_answer == "piranha" or lake_answer == "P" or lake_answer == "p":
        time.sleep(2)
        print(" ")
        print("You scramble into the water just as the lioness steps forward and unleashes a roar that shakes every tree in the Python Jungle...")
        time.sleep(2)
        print(" ")
        print("You plunge beneath the surface of the water and hold your breath until it feels like your lungs may explode...")
        time.sleep(2)
        print(" ")
        print("... ... ...")
        print(" ")
        time.sleep(5)
        print("... ... ...")
        time.sleep(2)
        print(" ")
        print("When you come back up to the surface, you are relieved there is no sign of the lioness, and to breathe some oxygen!")
        time.sleep(2)
        print(" ")
        print("But then... OUCH")
        time.sleep(3)
        print(" ")
        print("What---- what was-----")
        time.sleep(2)
        print(" ")
        print("There is a piranha munching on your foot!!!!!")
        time.sleep(2)
        print(" ")
        print("Swiiiiiiiiim! " + name.upper() + ", SWIM AS FAST AS YOU CAN!!")
        time.sleep(2)
        print(" ")
        print("... ... ...")
        print(" ")
        time.sleep(2)
        print("You are back on shore. Quivering, and bleeding a little. But you are safe for now. Well done.")
        print("")
    elif lake_answer == "Lioness" or lake_answer == "lioness" or lake_answer == "L" or lake_answer == "l":
        time.sleep(2)
        print(" ")
        print("Shakily, you brandish the axe, and begin to back into the trees.")
        time.sleep(2)
        print(" ")
        print("But, really... come on " + name + "... This is lioness versus human.")
        time.sleep(2)
        print(" ")
        print("What did you think was going to happen?")
        time.sleep(2)
        print(" ")
        print("I can tell you what does happen...")
        time.sleep(2)
        print(" ")
        print("The lioness is on top of you before you even have the chance to scream. And you never even got the chance to eat that last mango.")
        time.sleep(1)
        print(" ")
        print("Farewell, " + name + ". You were so close to the final level! Maybe see you again?...")
        print("")
        response = input("Play again? [Yes/No]")
        if response == "yes" or response == "YES" or response == "Yes":
            level_2() 
        else:
            print("***Thank you for playing PYTHON TEMPLE!***")
            quit()
        
       
    else:
        time.sleep(2)
        print(" ")
        print("Dude, I don't have a clue what you're on about.")
        lake_decision()
        
def mango_retry():
    mango_try_again = input(name + ", do you try again? [Yes / No] ---  ")
    if mango_try_again == "Yes" or mango_try_again == "yes" or mango_try_again == "Y" or mango_try_again == "y":
        time.sleep(2)
        print(" ")
        print("You start over, whispering '" + name + ", you got this... These mangoes will be yours...'")
        print(" ")
        time.sleep(2)
        print("And, as it turns out, these mangoes ARE now yours!")
        print(" ")
        time.sleep(2)
        print("You hold the mangoes in your hands, and smile for the first time today.")
        print(" ")
        time.sleep(2)
        print("Today is the day that you will EAT. Well done!")
        print(" ")
        time.sleep(2)
        print("The taste of the mangoes blows your mind. You devour them as you continue on, strengthened.")
    elif mango_try_again == "No" or mango_try_again == "no" or mango_try_again == "N" or mango_try_again == "n":
        time.sleep(2)
        print(" ")
        print("Without these mangoes, your blood sugar drops, as does your morale...")
        print(" ")
        time.sleep(2)
        print("You become so weak and unfocused that you barely notice when a group of gorillas, in pursuit of the mango tree, rush past you and crush you.")
        print(" ")
        time.sleep(2)
        print("Farewell, " + name + ". The Python Jungle is your permanent home now.")
        print("")
        response = input("Play again? [Yes/No]")
        if response == "yes" or response == "YES" or response == "Yes":
            level_2() 
        else:
            print("***Thank you for playing PYTHON TEMPLE!***")
            quit()
        
    else:
        time.sleep(2)
        print(" ")
        print("You are making no sense, " + name + "! Please tell me again.")
        mango_retry()

def mango_decision():
    mango_answer = input("So, " + name + ", which will it be? [Axe / Climb / Nothing] ---  ")
    if mango_answer == "axe" or mango_answer == "Axe" or mango_answer == "a" or mango_answer == "A":
        time.sleep(2)
        print(" ")
        print("With all of your might, you launch your axe at a cluster of mangoes...")
        time.sleep(2)
        print(" ")
        print("Then, all in a second...")
        time.sleep(2)
        print(" ")
        print("THUD!")
        print(" ")
        time.sleep(2)
        print("Ohhh, jeez " + name + "... The axe comes back down at the speed of light and takes you out.")
        print(" ")
        time.sleep(3)
        print("You lay in the undergrowth of Python Jungle for hours, passed out, and when you awaken...")
        time.sleep(3)
        print(" ")
        print("You are being carried in the mouth of a tiger.")
        time.sleep(3)
        print(" ")
        print("Goodbye, " + name + ". Better luck next time.")
        print("")
        response = input("Play again? [Yes/No]")
        if response == "yes" or response == "YES" or response == "Yes":
            level_2() 
        else:
            print("***Thank you for playing PYTHON TEMPLE!***")
            quit()
        
        
    elif mango_answer == "climb" or mango_answer == "Climb" or mango_answer == "c" or mango_answer == "C":
        time.sleep(2)
        print(" ")
        print("You crack you knuckles and neck, preparing for the climb...")
        print(" ")
        time.sleep(2)
        print("You fuse with the tree trunk, fighting your fatigue, spurred on by your hunger...")
        print(" ")
        time.sleep(3)
        print("... ... ...")
        print(" ")
        time.sleep(1)
        print("Edging closer to a mango...")
        print(" ")
        time.sleep(1)
        print("And...")
        print(" ")
        time.sleep(1)
        print("Huzzah!!! The Python Jungle has rewarded your determination, " + name + ". In your hand, you hold a mango.")
        time.sleep(2)
        print(" ")
        print("But... Wait...")
        time.sleep(1)
        print(" ")
        print("This mango is ROTTEN!")
        print(" ")
        time.sleep(2)
        print("You let out a groan to the jungle. It remains indifferent.")
        print(" ")
        time.sleep(2)
        mango_retry()
    elif mango_answer == "Nothing" or mango_answer == "nothing" or mango_answer == "N" or mango_answer == "n":
        time.sleep(2)
        print(" ")
        print("You continue onward, beginning to hallucinate that you can see a Sainsburys in the distance...")
        print(" ")
        time.sleep(2)
        print("Great! You think. I'll get some falafel and orange juice.")
        print(" ")
        time.sleep(2)
        print("Turns out the Sainsburys is a quicksand swamp.")
        print(" ")
        time.sleep(2)
        print("Without the strength the mangoes could have given your brain, you forget to be still in the quicksand, and instead panic...")
        print(" ")
        time.sleep(2)
        print("The Python Jungle is brutal. Sorry " + name + ". Seeeeeya.")
        print("")
        response = input("Play again? [Yes/No]")
        if response == "yes" or response == "YES" or response == "Yes":
            level_2() 
        else:
            print("***Thank you for playing PYTHON TEMPLE!***")
            quit()
        
    else:
        time.sleep(2)
        print(" ")
        print("Your brain is so full of mangoes (or the lackof) that you are making no sense! Try again!")
        mango_decision()
            

def water_decision():
    water_answer = input("Do you decide to? [Yes / No] ---  ")
    if water_answer == "yes" or water_answer == "Yes" or water_answer == "YES" or water_answer == "Y" or water_answer == "y":
        time.sleep(2)
        print(" ")
        print("Ah, big mistake " + name + ", the water isn't too helpful, and you don't come across any more for hours. Your body dries up as you sweat out the last of your reserves. You fall into delirium, eventually dehydrating to death.")
        time.sleep(1)
        print(" ")
        print("Better luck next time, " + name + ".")
        print("")
        response = input("Play again? [Yes/No]")
        if response == "yes" or response == "YES" or response == "Yes":
            level_2() 
        else:
            print("***Thank you for playing PYTHON TEMPLE!***")
        quit()
        
    elif water_answer == "no" or water_answer == "No" or water_answer == "NO" or water_answer == "N" or water_answer == "n":
        time.sleep(2)
        print(" ")
        print("Good choice! It seems you are becoming a jungle warrior, " + name + ". The water will be much more valuable in keeping you hydrated. You continue onward, transforming the pain into motivation.")
    else:
        time.sleep(2)
        print(" ")
        print("Say what?!... Please try again.")
        water_decision()

def level_2():
    global name

    time.sleep(1)
    print(" ")
    print(name + ", to your surprise, you land not into doom,")
    print(" ")
    time.sleep(2)
    print("...but worse...")
    print(" ")
    time.sleep(2)
    print("...THE NEST OF SOME EXTREMELY TERRITORIAL FIRE ANTS!!!!")
    time.sleep(2)
    print(" |       /")
    print("  |     /")
    print("   |.-./")
    print("  (o|^/o)  _   _   _     __")
    print("   ./ |.  ( )-( )-( ) .-'  '-.")
    print("    {-} |(//  ||   ||/ (   )) '-.")
    print("         //-__||__.-||.       .-'")
    print("        (/    ()     ||)'-._.-'")
    print("        ||    ||      ||")
    print("        ('    ('       ')")
    time.sleep(3)
    print(" ")
    print("The fire ants pinch into your every crevice, spreading flames of pain with no remorse...")
    time.sleep(3)
    print(" ")
    print("You scream, but the plants and animals of the jungle don't have much sympathy...")
    time.sleep(3)
    print("In fact, a lot of them would probably like to silence you by eating you for dinner.")
    time.sleep(4)
    print(" ")
    print("You realise you have an old, crumpled plastic bottle in your back pocket, half-filled with water.")
    time.sleep(2)
    print("You are desperate to soothe your fire ant bites with it.")
    print(" ")
    time.sleep(3)
    water_decision()
    time.sleep(2)
    print(" ")
    print("... ... ...")
    time.sleep(2)
    print(" ")
    print("You delve deeper into the buzzing and teeming Python Jungle.")
    time.sleep(3)
    print(" ")
    print("What a mystery this all is!")
    time.sleep(3)
    print(" ")
    print("Suddenly you catch the scent of sweetness. Your belly gurgles at the thought of some nourishment.")
    time.sleep(3)
    print(" ")
    print("You look upwards, and as your eyes focus, you whisper to yourself 'Holy crackers, " + name + "!'")
    time.sleep(3)
    print(" ")
    print("Above you, hanging like vivid orange gems.....")
    time.sleep(3)
    print(" ")
    print("         *    * *")    
    print("    *  *    *     *")
    print("  *  *    *     *  *")
    print(" *     *    *  *      *")
    print(" * *   *    *    *    * *")
    print("*     *  *    * * .#  *   *")
    print("*   0 0*     * #.  .# *   *")
    print(" *  0  #.  #: #'' * * 0   *")
    print("  *   *0 * ''#. ##''0 0  *")
    print("   *   0  0''### 0  00  *")
    print("         ''##")
    print("          ##.")
    print("          .##:")
    print("          :###")
    print("          ;###")
    print("        ,####.")
    time.sleep(1)
    print("A RIPE MANGO TREE!!!!!")
    print(" ")
    time.sleep(2)
    print("Your hefty axe hangs from your belt, as your feet stand on the edge of the huge root of the mango tree, leading up to the trunk and the fruits.")
    print(" ")
    time.sleep(3)
    print("You could launch your axe at the mangoes, hoping to loosen them. Or you could climb your way to them.")
    print(" ")
    time.sleep(2)
    print("Or, of course, you could do nothing...")
    print(" ")
    time.sleep(3)
    mango_decision()
    time.sleep(2)
    print(" ")
    print("... ... ...")
    time.sleep(2)
    print(" ")
    print("No offence, " + name + ", but you smell like, well... like you've been roaming in a humid jungle for...")
    time.sleep(2)
    print(" ")
    print("Umm... How long has it been?")
    time.sleep(3)
    print(" ")
    print("You are desperate to cool off,")
    time.sleep(1)
    print("to feel a little cleaner,")
    time.sleep(1)
    print("to finally soothe your fire ant bites,")
    time.sleep(1)
    print("and of course, to gulp some fresh(ish) water...")
    print(" ")
    time.sleep(2)
    print("So, just imagine your delight when the dense green finally gives way to the shore of a jungle lake!")
    time.sleep(2)
    print(" ")
    print("   				             ‘‘‘/// ///  ’’’")
    print("				            --- (___) ---")
    print("				           ‘‘‘ /// /// ’’’")
    print(" ")
    print(" ")
    print("____ ---- __ -_ _ ______  _ __-- __  _ __- _ __  _ ______  _ __  _")
    print("                     .,- = - = - = - = - = - = - = - = - = - = - =")
    print("                             .,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("                                    .,______  _ _______  __ __  _ ")
    print("                                           .,= - = - = - = -  = - ")
    print("                                                .,~~~~~~~~~~~~~~~~")
    print("                                                      .,__ ___  _ ")
    print("                                                          .,= = - ")
    print("                                                            .,~~~~")
    print("				                              ,.,")
    time.sleep(2)
    print(" ")
    print("To the blue velvet sky above, you shout in excitement...")
    time.sleep(2)
    shout = input("Wait, what do you shout?  ")
    print(" ")
    time.sleep(1)
    print("Ah, yes of course... you shout: '" + shout.upper() + "!!!!!!'")
    time.sleep(2)
    print(" ")
    print("But, c'mon " + name + ", by now you should know things aren't that simple...")
    time.sleep(2)
    print(" ")
    print("Just as you set down your one remaining mango and axe, you notice an ancient painting on a nearby rock...")
    time.sleep(2)
    print(" ")
    print("             |")
    print("             |")
    print("            ,|.")
    print("           ,|/.")
    print("         ,' .V. `.")
    print("        / .     . |")
    print("       /_`       '_|")
    print("      ,' .:     ;, `.")
    print("      |@)|  . .  |(@|")
    print(" ,-._ `._';  .  :`_,' _,-.")
    print("'--  `-| /,-===-.| /-'  --`")
    print("(---- _|  ||___||  |_  ----)")
    print("`._,-'  |  `-.-'  /  `-._,'")
    print("         `-.___,-' ")
    time.sleep(3)
    print(" ")
    print("In faded red ink...")
    time.sleep(2)
    print(" ")
    print("A PIRANHA!")
    time.sleep(2)
    print(" ")
    print("You know this must be a warning about the lake, that the flesh-eating fish rampage the waters...")
    time.sleep(2)
    print(" ")
    print("Suddenly, you hear a rustling behind in the bushes...")
    time.sleep(2)
    print(" ")
    print("Holding your breath, and turning slowly... you whimper as you see her:")
    time.sleep(2)
    print(" ")
    print("A majestic, deadly lioness.")
    time.sleep(2)
    print(" ")
    print("She is staring right at you.")
    time.sleep(2)
    print(" ")
    print("Your vision tunnels and your knees shapeshift into jelly as you realise you must make a decision.")
    time.sleep(1)
    print("And " + name + ", that decision has got to be riiiiiiiiiight now.")
    time.sleep(2)
    print(" ")
    lake_decision()
    time.sleep(4)
    print(" ")
    print("Just who has subjected you to this challenge, " + name + "?")
    time.sleep(3)
    print(" ")
    print("You plan to write them a strongly worded email once this is all over.")
    time.sleep(2)
    print(" ")
    print("Assuming it will soon be over...?!?")
    time.sleep(3)
    print(" ")
    print("For now, you wrap yourself in some palm leaves in a small cave by the lake, eat your last mango for supper and try to get some rest.")
    time.sleep(3)
    print(" ")
    print("Around you, Python Jungle is dense and deafening with animal calls and chaos.")
    time.sleep(3)
    print(" ")
    print("You close your eyes, hardly believing the day behind you really happened.") 
    print(" ")
    time.sleep(2)
    print("Goodnight, " + name + ".")
    print(" ")  
    time.sleep(2)
    print("                        |")
    print("                    |       /")
    print("                      .-''-.")
    print("                 --  /     |  --")
    print("`~~^~^~^~^~^~^~^~^~^-=======-~^~^~^~~^~^~^~^~^~^~^~`")
    print("`~^_~^~^~-~^_~^~^_~-=========- -~^~^~^-~^~^_~^~^~^~`")
    print("`~^~-~~^~^~-^~^_~^~~ -=====- ~^~^~-~^~_~^~^~~^~-~^~`")
    print("~^~^~-~^~~^~-~^~~-~^~^~-~^~~^-~^~^~^-~^~^~^~^~~^~-`")
    lion_decision()






import time
global name



def game_start():
        
        global name

        print("'W---W-----Where am I???!' you howl as you wake up...")
        time.sleep(2)
        print("")
        print("Welcome explorer... Take a deep breath. You are in Python Jungle...")
        name = input("Many fun and games await you, explorer... Now let's get this party started... Please tell me your name?  ")
        time.sleep(1)
        print("Welcome to the unknown, {}.".format(name))
        time.sleep(2)
        print("As you awaken in the middle of Python Jungle, you realise in horror that a mythical creature is fast approaching you!")

        yes_no = ["yes", "no"]
        directions = ["left", "right", "forward", "backward"]

        response = ""
        while response not in yes_no:
            response = input("Shall we get moving??!\nyes/no\n")
            if response == "yes":
                print("You are a brave soul, "+ name +". \n")
            elif response == "no":
                print("You are the creatures dinner now. Goodbye, " + name + ".")
                response = input("Play again? [Yes/No]")
                if response == "yes" or response == "YES" or response == "Yes":
                    game_start() 
                else:
                    print("***Thank you for playing PYTHON TEMPLE!***")
                    quit()
            else: 
                print("I didn't understand that.\n")


        response = ""
        while response not in directions:
            print("To your left, you see an open area between the trees seemingly going on for infinity, and there is an axe to collect on the way.")
            time.sleep(2)
            print("To your right, there is a large, gnarled vine wall with an axe resting at the top.")
            time.sleep(2)
            print("Behind, is a narrow passage between two trees that leads to a drop with an axe.")
            time.sleep(2)
            print("Forward leads to the huge, mystical jungle creature.\n")
            time.sleep(2)
            response = input("What direction do you move?\nleft/right/forward/backward\n")
            if response == "forward":
                print("The creature eats you. Farewell, " + name + ".")
                response = input("Play again? [Yes/No]")
                if response == "yes" or response == "YES" or response == "Yes":
                    game_start() 
                else:
                    print("***Thank you for playing PYTHON TEMPLE!***")
                    quit()

            elif response == "right":
                print("You climb the vine wall, collecting an axe on the way but instantly hit a land slide.\n")
                time.sleep(2)
                print("")
                print("Suddenly you are hurtling downwards, wondering when you will land on solid ground, and what you will find there...")
                level_2()
            elif response == "left":
                print("You collect an axe but the floor instantly collapses.\n")
                time.sleep(2)
                print("")
                print("Suddenly you are hurtling downwards, wondering when you will land on solid ground, and what you will find there...")
                level_2()
            elif response == "backward":
                print("You collect an axe on the way but instantly hit a land slide.\n")
                time.sleep(2)
                print("")
                print("Suddenly you are hurtling downwards, wondering when you will land on solid ground, and what you will find there...")
                level_2()
                
            else:
                print("I didn't understand that.\n")
                game_start()
            
game_start()


#THINGS TO DO:#
#TEXT EDITING
#LEVEL 3 ADDITION AND LINKAGE TO LEVEL 4
#CHECK THAT ALL RAW_INPUT HAVE BEEN CHNAGED TO INPUT
#EVERYONE PLAY THROUGH ALL SCENARIOS TO CHECK FOR DEAD ENDS
#SOME MISSING BITS NOTED BY TEXT